40-Develop/gpm_web/Models/API_Models/GatePassForm.cs
using System;
using Microsoft.Extensions.Logging;
using CTX = gpm.Efc.dbsets;
using EFC = gpm.Efc;
using GC = gpm.Common;
using GCE = gpm.Common.Enums;
using SE = gpm_web.Enums;
using SC = gpm_web.Consts;
using SL = gpm_web.Lookups;
using SLD = gpm_web.Lookups.DD_Lookup;
using IA = gpm_web.Infra;
using ML = gpm_web.Models;
using AM = gpm_web.API_Models;
using stCode = gpm.Common.Enums.ErrorCode;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace gpm_web.API_Models
{
	/// <summary>
	/// Convenienve format for API Usage
	/// </summary>
	public class GatePassForm
	{
		[Required]
		[Range(0, uint.MaxValue)]
		public int GatePassId { get; set; }

		[Required]
		[EnumDataType(typeof(SE.GATE_PASS_TYPE))]
		public SE.GATE_PASS_TYPE PassType { get; set; }

		/// <summary>
		/// Required for Update and for Search
		/// </summary>
		/// <value></value>
		[Range(0, uint.MaxValue)]
		public int PassNum { get; set; }

		public DateTime IssueDate { get; set; }

		public int PartyCount { get; set; }

		/// <summary>
		/// Required for updates.
		/// </summary>
		/// <value></value>
		[Range(1, uint.MaxValue)]
		public int Department { get; set; }

		[EnumDataType(typeof(SE.VISIT_TYPE))]
		public SE.VISIT_TYPE VisitType { get; set; }

		public string HospitalNum { get; set; }

		[MaxLength(10)]
		public string MobileNum { get; set; }

		public bool SupplyDelivery { get; set; }

		[StringLength(60)]
		public string PersonMeeting { get; set; }

		public bool HasResources { get; set; }

		[StringLength(20)]
		public string WheelchairNum { get; set; }

		public bool HasVehicle { get; set; }

		[EnumDataType(typeof(SE.VEHICLE_TYPE))]
		public SE.VEHICLE_TYPE VehicleType { get; set; }

		[StringLength(24)]
		public string VehiclePlateNum { get; set; }

		[StringLength(255)]
		public string Note { get; set; }

		public DateTimeOffset TimeIn { get; set; }

		public DateTimeOffset? TimeOut { get; set; }

		public DateTimeOffset? StepOut { get; set; }

		[EnumDataType(typeof(SE.GATE_PASS_STATUS))]
		public SE.GATE_PASS_STATUS Status { get; set; }

		/// <summary>
		/// Convert from gpm_web.API_Models.GatePassForm to gpm.Efc.dbsets.GatePasses format
		/// </summary>
		/// <returns>shallow copy of this instance in gpm.Efc.dbsets.GatePasses format</returns>
		public CTX.GatePasses ToModel() => new CTX.GatePasses()
		{
			HasResources = this.HasResources ? (int)SE.YES_NO.YES : (int)SE.YES_NO.NO,
			HasVehicle = this.HasVehicle ? (int)SE.YES_NO.YES : (int)SE.YES_NO.NO,
			SupplyDelivery = this.SupplyDelivery ? (int)SE.YES_NO.YES : (int)SE.YES_NO.NO,
			IssueDate = this.IssueDate,
			TimeIn = this.TimeIn,
			StepOut = this.StepOut,
			TimeOut = this.TimeOut,
			Department = this.Department,
			GatePassId = this.GatePassId,
			PartyCount = this.PartyCount,
			PassNum = this.PassNum,
			Status = (int)this.Status,
			PassType = (int)this.PassType,
			VehicleType = (int)this.VehicleType,
			VisitType = (int)this.VisitType,
			HospitalNum = this.HospitalNum,
			MobileNum = this.MobileNum,
			Note = this.Note,
			PersonMeeting = this.PersonMeeting,
			VehiclePlateNum = this.VehiclePlateNum,
			WheelchairNum = this.WheelchairNum,
		};

	}
}

40-Develop/gpm_web/Controllers/GatePassController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using gpm_web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Text;
using Microsoft.EntityFrameworkCore;

using Microsoft.Extensions.Logging;
using CTX = gpm.Efc.dbsets;
using EFC = gpm.Efc;
using GC = gpm.Common;
using GCE = gpm.Common.Enums;
using SE = gpm_web.Enums;
using SC = gpm_web.Consts;
using SL = gpm_web.Lookups;
using SLD = gpm_web.Lookups.DD_Lookup;
using IA = gpm_web.Infra;
using ML = gpm_web.Models;
using AM = gpm_web.API_Models;
using BO = gpm_web.BizObjs;
using stCode = gpm.Common.Enums.ErrorCode;

namespace gpm_web.Controllers
{
	/// <summary>
	/// 
	/// </summary>
	public partial class GatePassController : Infra.GPMController
	{
		public IA.TokenCounter Token_Counter { get; set; }
		public IA.DayCapacityCounters Dept_Day_Caps { get; set; }
		public SL.DD_Lookup DDHelp { get; set; }
		public BO.GatePassBZ GPBizObj { get; set; }

		public GatePassController(ILogger<GatePassController> logger, GC.IAppSettingContainer App_Config, gpm.Efc.dbsets.GPM_DBContext db_context, IA.TokenCounter token_counter, IA.DayCapacityCounters dept_cap_counter, SL.DD_Lookup dd_helper, BO.GatePassBZ boGP)
			: base(logger, App_Config, db_context)
		{
			log.LogInformation("==> GatePassController:CTOR");
			Token_Counter = token_counter;
			Dept_Day_Caps = dept_cap_counter;
			DDHelp = dd_helper;
			GPBizObj = boGP;
		}

		[Authorize]
		public IActionResult TypeSelect()
		{
			return View(new CTX.GatePasses());
		}

		[Authorize]
		public IActionResult DeptSelect()
		{
			log.LogDebug("User.Identity.IsAuthenticated = {0}", User.Identity.IsAuthenticated);
			return View(Dept_Day_Caps.AvailaibleCaps(dbcontext));
		}

		// Refactor done
		[Authorize]
		public IActionResult NewPassPatient(int deptid = 0, int vtype = 0)
		{
			log.LogInformation("==> NewPassPatient");
			CTX.GatePasses loNewGPP = GPBizObj.NewPassPatient(deptid, vtype);
			if (loNewGPP == null)
			{
				PostError("Invalid values for Department and Type. Try again with valid values.");
				return RedirectToAction("DeptSelect");
			}
			ViewData.Model = loNewGPP;
			return View();
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="id">Pass ID, for which the vehicle pass is to be created</param>
		/// <returns></returns>
		[Authorize]
		public IActionResult NewPassVehicle(int id = 0)
		{
			log.LogInformation("==> NewPassVehicle");
			CTX.GatePasses loNewGPP = GPBizObj.NewPassVehicle(id);
			if (loNewGPP == null)
			{
				PostError("Invalid value for Root Pass. Try again with valid values.");
				return RedirectToAction("TypeSelect");
			}
			string lsTest = loNewGPP.AddOn.ToLocalTime().ToString(SC.FORMATS.DATE_TIME_FORMAT);
			ViewData.Model = loNewGPP;
			ViewBag.RootPassNum = loNewGPP.Note;    // TD001: NOT a good idea, move to ideal usage ASAP.
			return View();
		}

		[Authorize]
		public IActionResult NewPassVisitor(int vtype = 0)
		{
			return View();
		}

		[Obsolete("Not to be used. Use Type select directly.", true)]
		[Authorize]
		public IActionResult NewPassEmergency(int vtype = 0)
		{
			CTX.GatePasses gpEmergency = new CTX.GatePasses()
			{
				PassType = (int)SE.GATE_PASS_TYPE.EMERGENCY,
				SupplyDelivery = 0,
			};
			if (gpEmergency.SupplyDelivery == null)
			{
				gpEmergency.SupplyDelivery = 0;
			}
			return View();
		}

		// Refactor done
		[Authorize]
		public IActionResult PassStatus(int linkid, int status)
		{
			CTX.GatePasses lGP = GPBizObj.PatchPassStatus(linkid, status);
			return RedirectToAction("Edit", new { id = linkid });
		}

		// Refactor done
		[Authorize]
		public IActionResult Find(CTX.GatePasses GatePass)
		{
			List<CTX.GatePasses> lstResults = GPBizObj.FindPasses(GatePass);
			ViewBag.SearchFilter = GatePass;
			return View(lstResults);
		}

		[Authorize]
		public async Task<IActionResult> FindPagedAsync(ML.SearchFormGatepass SearchFilter)
		{
			ML.SearchResultsGatepass loResults;
			// loResults = GPBizObj.FindPagedAsync(SearchFilter).Result;
			loResults = await GPBizObj.FindPagedAsync(SearchFilter);
			return View(loResults);
		}

		[Authorize]
		public IActionResult FindOne(int id)
		{
			ViewBag.SearchFilter = id;
			if (!Request.Query.ContainsKey("id"))
			{
				ViewBag.SearchFilter = -1;
				return View(null);
			}
			CTX.GatePasses loResult = GPBizObj.FindPass(id);
			if (loResult == null)
			{
				return View(loResult);
			}
			loResult.IsPassOfInterest = true;
			if (loResult.RootGatePassNavigation == null)
			{
				loResult.StatusName = DDHelp.DisplayText((int)SE.DDCategories.GATE_PASS_STATUS, loResult.Status, true);
				ViewBag.RootPassNum = DDHelp.FormattedPassNumber(loResult.PassType, loResult.PassNum);
			}
			else
			{
				loResult.StatusName = DDHelp.DisplayText((int)SE.DDCategories.GATE_PASS_STATUS, loResult.RootGatePassNavigation.Status, true);
				ViewBag.RootPassNum = DDHelp.FormattedPassNumber(loResult.RootGatePassNavigation.PassType, loResult.RootGatePassNavigation.PassNum);
			}
			return View(loResult);
		}

		// Refactor done
		[Authorize]
		public IActionResult Put([FromForm]CTX.GatePasses GatePass, [FromRoute]int? id)
		{
			log.LogDebug("==> Put");
			return View("Edit", GPBizObj.CreateGatepass(GatePass, UserData));
		}

		// Refactor done
		[Authorize]
		public IActionResult Edit(int? id)
		{
			log.LogDebug("==> Put");
			int LinkID = id ?? ViewBag.LinkID ?? 0;
			if (id < 1)
			{
				log.LogError("Invalid login ID {0}. Cannot proceed");
				return new System.ArgumentOutOfRangeException() as IActionResult;
			}
			CTX.GatePasses loGPTree = GPBizObj.GetPassForEdit(id);
			if (loGPTree == null)
			{
				return new NotFoundResult();
			}
			return View(loGPTree);
		}

		[Authorize()]
		public IActionResult Print(int id = 0)
		{
			log.LogDebug("==> Put");
			return View();
		}

		// Refactor done
		[Authorize]
		public IActionResult Update(CTX.GatePasses gatepass)
		{
			if (!ModelState.IsValid)
			{
				ViewData[SC.KEYS.ERROR_VIEWBAG] = "Model validation failed!";
				return RedirectToAction("Edit", new { id = gatepass?.GatePassId ?? 0 });
			}
			CTX.GatePasses loGP = GPBizObj.UpdatePass(gatepass, UserData);
			if (loGP == null)
			{
				// Post error message for display.
			}
			return RedirectToAction("Edit", new { id = gatepass?.GatePassId ?? 0 });
		}

	}
}

40-Develop/gpm_web/Views/Gatepass/DeptSelect.cshtml
@using ML = gpm_web.Models;
@using SL = gpm_web.Lookups;

@inject SL.DD_Lookup DDHelp;

@{
ViewData["Title"] = "Pass Dept Select";
Layout = "_Layout_Gpm_User";

// TODO: Map to enums.
int VisitTypeFirst = 1;
int VisitTypeRevisit = 2;

}
@model List<ML.DeptCapValues>;

	<div class="container-fluid text-center">
		<div class="h2 display-4 mt-3 text-cstm-pri-dark shadow-text-outline">New Patient Gate Pass</div>
		<div class="h3 mb-3 text-cstm-sec-dark shadow-text-outline">Select a Department and Visit Type</div>
	</div>

	<p>
		@* this should be a comment not visible on the browser *@
	</p>

	<div class="row">

		@foreach (ML.DeptCapValues vDept in Model)
		{
		if (vDept.CapFirst == 0 && vDept.CapRevisit == 0 ) { continue; }
		<div class="col-12 col-md-6 col-lg-4 col-xl-3">
			<div class="card shadow-heavy m-2 mt-4">
				<div class="h3 display-4 card-header text-center bg-light p-0">@vDept.DeptName (u @(vDept.UsedFirst + vDept.UsedRevisit))</div>
				<div class="card-body p-2">
					<div class="d-flex h4 text-cstm-dark m-0 mb-1">
						<div class="flex-fill text-center">First Visit</div>
						<div class="flex-fill text-center">Re-Visit</div>
					</div>
					<div class="d-flex">
						<a asp-controller="GatePass"
						   asp-action="NewPassPatient"
						   asp-route-deptid="@vDept.DeptCode"
						   asp-route-vtype="@VisitTypeFirst"
						   class="btn btn-lg btn-cstm-sec-light flex-fill shadow-light h2 mr-2">@(vDept.CapFirst -
							vDept.UsedFirst)</a>
						<a asp-controller="GatePass"
						   asp-action="NewPassPatient"
						   asp-route-deptid="@vDept.DeptCode"
						   asp-route-vtype="@VisitTypeRevisit"
						   class="btn btn-lg btn-cstm-alt-2-light flex-fill shadow-light h2 ml-2">@(vDept.CapRevisit -
							vDept.UsedRevisit)</a>
					</div>
				</div>
			</div> <!-- Card -->
		</div> <!-- Column -->
		}

	</div>
	<hr>


	<!-- ========================================================================================================== -->

40-Develop/gpm_web/Views/Gatepass/Find.cshtml
@using Microsoft.Extensions.Logging;
@using CTX = gpm.Efc.dbsets;
@using EFC = gpm.Efc;
@using GC = gpm.Common;
@using GCE = gpm.Common.Enums;
@using SE = gpm_web.Enums;
@using SC = gpm_web.Consts;
@using SL = gpm_web.Lookups;
@using SLD = gpm_web.Lookups.DD_Lookup;
@using IA = gpm_web.Infra;
@using ML = gpm_web.Models;
@using stCode = gpm.Common.Enums.ErrorCode;

@inject SL.DD_Lookup DDHelp;
@inject ILogger<gpm_web.Controllers.GatePassController> log;

@{
	ViewData["Title"] = "Search Gatepass";
	Layout = "_Layout_Gpm_User";
	@model List<CTX.GatePasses>;
	List<ML.DD_Item> lstDepts = DDHelp.GetItems(SE.DDCategories.DEPTS_ALL, true); //.OrderBy(y => y.DisplaySeq).ToList();

	string lsDateFmt = SC.FORMATS.DATE_SHORT_FORMAT;
	CTX.GatePasses lmSearch = ViewBag.SearchFilter ?? new CTX.GatePasses (){ IssueDate = DateTime.Today };
	string lsDateEdit = lmSearch.IssueDate.ToString("yyyy-MM-dd");
	log.LogDebug("Inspect values");
}
@functions{
	string ActiveClass(bool FlagVal){
		return FlagVal ? "" : SC.TAGS.OPTION_DISABLED;
	}
	string PutText(string StringToPut){
		return StringToPut;
	}
}



<div class="container-fluid my-3">

	<!-- justify-content-end -->
	<div class="row">

		<!-- Filter panel -->
		<div class="col-12 col-sm-9 col-md-6 col-lg-4 col-xl-3 border-right border-cstm-pri pr-2	">

			<div class="h1 display-4 text-cstm-pri-dark shadow-text-outline">Search Passes:
			</div>

			<!-- ========================================================================================================== -->
			<form method="POST"
					id="frmActive"
					name="frmActive"
					class="mx-1 my-4 p-0">
				<div class="row">

					<div class="col-12">
						<input type="hidden"
								id="SearchType"
								name="SearchType"
								value="2">
						<input type="submit"
								class="btn btn-outline-cstm-pri-light border-cstm-dark text-cstm-alt-1-dark shadow-light w-100"
								value="Find all Active Passes"
								id="getAll"
								name="getAll">
					</div>

				</div>
			</form>


			<!-- ========================================================================================================== -->
			<form id="frmToken"
					name="frmToken"
					class="shadow-outline mx-1 my-4 p-2">
				<div class="row">

					<div class="col-12">
						<div class="col-form-label-lg text-cstm-dark">By Pass Number and Date:</div>
						<input type="hidden"
								id="SearchType"
								name="SearchType"
								value="1">
					</div>
					<div class="col-6">
						<div class="form-group">
							<label for="PassNum">Pass Number:</label>
							<input class="form-control border-cstm-alt-1"
									type="number"
									id="PassNum"
									name="PassNum"
									min="1"
									value=""
									step="1">
						</div>
					</div>
					<div class="col-6">
						<div class="form-group">
							<label for="IssueDate">Issue Date:</label>
							<input type="date"
									class="form-control border-cstm-alt-1"
									id="IssueDate"
									name="IssueDate"
									value="@lsDateEdit">
						</div>
					</div>
					<div class="col-12">
						<input type="submit"
								class="btn btn-outline-cstm-pri-light border-cstm-dark text-cstm-alt-1-dark shadow-light mb-3 w-100"
								value="Find"
								id="getByToken"
								name="getByToken">
					</div>
					<div class="col-12">
						<span class="field-validation-valid text-danger cstm-text-error"
								data-valmsg-for="PassNum"
								data-valmsg-replace="true"></span>
					</div>

				</div>
			</form>



			<!-- ========================================================================================================== -->
			<form id="frmFilter"
					name="frmFilter"
					class="shadow-outline mx-1 my-4 p-2">

				<div class="row">
					<div class="col-12">
						<div class="col-form-label-lg text-cstm-dark">By Custom Filter:</div>
						<input type="hidden"
								id="SearchType"
								name="SearchType"
								value="3">
					</div>
				</div>

				<div class="row my-2">
					<div class="col-5 text-right">
						<label for="IssueDate"
								class="col-form-label">Date:
						</label>
					</div>
					<div class="col-7">
						<input type="date"
								class="form-control border-cstm-alt-1"
								id="IssueDate"
								name="IssueDate"
								value="@lsDateEdit">
					</div>
				</div>


				<div class="row my-2">
					<div class="col-5 text-right">
						<label for="Department"
								class="col-form-label">Department:
						</label>
					</div>
					<div class="col-7">
						<select class="custom-select cstm-select-bound"
								id="Department"
								name="Department"
								data-value-current="@int.MaxValue">
							<option value="@int.MaxValue">All Departments</option>
							@foreach (ML.DD_Item vOpt in lstDepts)
							{
								<option value="@vOpt.Value">@vOpt.Text</option>
							}
						</select>
					</div>
				</div>

				<div class="row my-2">
					<div class="col-5 text-right">
						<label for="Status"
								class="col-form-label">Status:
						</label>
					</div>
					<div class="col-7">
						<select class="custom-select cstm-select-bound"
								id="Status"
								name="Status"
								data-value-current="@int.MaxValue">
							<option value="@int.MaxValue">All Status</option>
							@foreach (ML.DD_Item vOpt in DDHelp.GetItems(SE.DDCategories.GATE_PASS_STATUS, false))
							{
								<option value="@vOpt.Value">@vOpt.Text</option>
							}
						</select>
					</div>
				</div>


				<div class="row my-2">
					<div class="col-5 text-right">
						<label for="PassType"
								class="col-form-label">Pass Type:
						</label>
					</div>
					<div class="col-7">
						<select class="custom-select cstm-select-bound"
								id="PassType"
								name="PassType"
								data-value-current="@int.MaxValue">
							<option value="@int.MaxValue">All Types</option>
							@foreach (ML.DD_Item vOpt in DDHelp.GetItems(SE.DDCategories.GATE_PASS_TYPE, false))
							{
								<option value="@vOpt.Value">@vOpt.Text</option>
							}
						</select>
					</div>
				</div>

				<div class="row my-2">
					<div class="col-5 text-right">
						<label for="PartyCount"
								class="col-form-label">Has Attendants:
						</label>
					</div>
					<div class="col-7">
						<select class="custom-select cstm-select-bound"
								id="PartyCount"
								name="PartyCount"
								data-value-current="@int.MaxValue">
							<option value="@int.MaxValue">Both</option>
							<option value="1"> With Attendants only </option>
							<option value="2"> Without Attendants only </option>
						</select>
					</div>
				</div>

				<div class="row my-2">
					<div class="col-5 text-right">
						<label for="VehicleType"
								class="col-form-label">Has Vehicle:
						</label>
					</div>
					<div class="col-7">
						<select class="custom-select cstm-select-bound"
								id="VehicleType"
								name="VehicleType"
								data-value-current="@int.MaxValue">
							<option value="@int.MaxValue">All</option>
							<option value="@int.MaxValue - 1000"> With any Vehicle</option>
							@foreach (ML.DD_Item vOpt in DDHelp.GetItems(SE.DDCategories.VEHICLE_TYPE, false))
							{
								<option value="@vOpt.Value">@vOpt.Text</option>
							}
						</select>
					</div>
				</div>

				<div class="row my-2">
					<div class="col-5 text-right">
						<label for="HasResources"
								class="col-form-label">Has Wheel chair:
						</label>
					</div>
					<div class="col-7">
						<select class="custom-select cstm-select-bound"
								id="HasResources"
								name="HasResources"
								data-value-current="@int.MaxValue">
							<option value="@int.MaxValue">All</option>
							@foreach (ML.DD_Item vOpt in DDHelp.GetItems(SE.DDCategories.YES_NO, true))
							{
								<option value="@vOpt.Value">@vOpt.Text</option>
							}
						</select>
					</div>
				</div>

				<div class="row my-2">
					<div class="col-12">
						<input type="submit"
								class="btn btn-outline-cstm-pri-light border-cstm-dark text-cstm-alt-1-dark shadow-light mb-3 w-100"
								value="Find"
								id="getByFilter"
								name="getByFilter">
					</div>
				</div>

			</form>



		</div> <!-- Column -->

		<!-- Results columns -->
		<div class="col-12 col-sm-12 col-md-6 col-lg-8 col-xl-9">
			<div class="text-monospace text-cstm-dark h3">Got @Model.Count records.</div>
			<table class="table table-striped table-hover p-0 m-0">
				<thead class="thead-dark">
					<tr>
						<th>Date</th>
						<th>Number</th>
						<th>Root Pass</th>
						<th>Dept.</th>
						<th>Type</th>
						<th>Party</th>
						<th>Veh?</th>
						<th>W?</th>
						<th>Status</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
				@foreach (CTX.GatePasses vGP in Model)
				{
					log.LogDebug("PASS = {0}, Root = {1}, Root-Type = {2}, Root-Num = {3}", vGP.PassNum, vGP.RootGatePass, vGP.RootGatePassNavigation?.PassType, vGP.RootGatePassNavigation?.PassNum);
					<tr>
						<td class="my-0 py-1">@vGP.IssueDate.ToString(lsDateFmt)</td>
						<td class="my-0 py-1">
							<a asp-controller="GatePass" asp-action="Edit" asp-route-id="@vGP.GatePassId" class="btn-link">@DDHelp.FormattedPassNumber(vGP.PassType, vGP.PassNum)</a>
							</td>
						<td class="my-0 py-1">@DDHelp.FormattedPassNumber(vGP.RootGatePassNavigation?.PassType ?? 0, vGP.RootGatePassNavigation?.PassNum ?? 0)</td>
						<td class="my-0 py-1">@DDHelp.DisplayText(3, vGP.Department, true) </td>
						<td class="my-0 py-1">@DDHelp.DisplayText(7, vGP.PassType, true) </td>
						<td class="my-0 py-1">@vGP.PartyCount</td>
						<td class="my-0 py-1">@DDHelp.DisplayText(1, vGP.HasVehicle, true) </td>
						<td class="my-0 py-1">@DDHelp.DisplayText(1, vGP.HasResources, true) </td>
						<td class="my-0 py-1">@DDHelp.DisplayText(8, vGP.Status, true) </td>
						<td class="my-0 py-1">
							<a asp-controller="GatePass" asp-action="Edit" asp-route-id="@vGP.GatePassId" class="btn-link">edit</a>
						</td>
					</tr>
				}
				</tbody>
			</table>
		</div>

	</div> <!-- Row -->


</div> <!-- container-fluid -->

40-Develop/gpm_web/Views/Gatepass/NewPassVehicle.cshtml
@using Microsoft.Extensions.Logging;
@using CTX = gpm.Efc.dbsets;
@using EFC = gpm.Efc;
@using GC = gpm.Common;
@using GCE = gpm.Common.Enums;
@using SE = gpm_web.Enums;
@using SC = gpm_web.Consts;
@using SL = gpm_web.Lookups;
@using SLD = gpm_web.Lookups.DD_Lookup;
@using IA = gpm_web.Infra;
@using ML = gpm_web.Models;
@using stCode = gpm.Common.Enums.ErrorCode;
@using System.Linq;

@inject SL.DD_Lookup DDHelp;
@inject ILogger<gpm_web.Controllers.GatePassController> log;

@model CTX.GatePasses;

@{
	ViewData["Title"] = "New Vehicle Pass";
	Layout = "_Layout_Gpm_User";
	string lsTagInterest = Model.IsPassOfInterest ? "pl-5" : "";
	<!-- ViewBag.RootPassNum = DDHelp.FormattedPassNumber(Model.PassType, Model.RootGatePass?? 0); -->
}

<div class="container-fluid my-3">
	<span class="text-danger">@Html.ValidationSummary(false)</span>

	<div class="row p-3 justify-content-end">
		<!-- Render Gate pass -->
		<div class="col-12 col-md-6 col-lg-6 col-xl-4">
			@await Html.PartialAsync("_PassVehicle", Model)
		</div>
	</div>
</div>

40-Develop/gpm_web/Views/Gatepass/NewPassVisitor.cshtml
<div class="display-1 h1">New Visitor Gate Pass</div>

40-Develop/gpm_web/Views/Gatepass/PassStatus.cshtml
<div class="display-1 h1">Gate Pass Status</div>

40-Develop/gpm_web/Views/Gatepass/Put.cshtml
<div class="display-1 h1">Save Gate pass, Never to be shown to User.</div>

40-Develop/gpm_web/Views/Gatepass/_PassStatusMenu.cshtml
<!-- To be implementes
1. Pass as arg, gatepass id

 -->

<a class="dropdown-item bg-cstm-sec-light border-cstm-dark"
	asp-controller="Gatepass"
	asp-route="PassStatus"
	asp-route-linkid="@Model.GatePassId"
	asp-route-status="6"
	>Cancel Pass</a>
<a class="dropdown-item bg-cstm-sec-light border-cstm-dark"
	asp-controller="Gatepass"
	asp-route="PassStatus"
	asp-route-linkid="@Model.GatePassId"
	asp-route-status="1"
	href="#">Step In</a>
<a class="dropdown-item bg-cstm-sec-light border-cstm-dark"
	asp-controller="Gatepass"
	asp-route="PassStatus"
	asp-route-linkid="@Model.GatePassId"
	asp-route-status="2"
	href="#">Step Out</a>
<a class="dropdown-item bg-cstm-sec-light border-cstm-dark"
	asp-controller="Gatepass"
	asp-route="PassStatus"
	asp-route-linkid="@Model.GatePassId"
	asp-route-status="3"
	href="#">Check Out</a>
<a class="dropdown-item bg-cstm-sec-light border-cstm-dark"
	asp-controller="Gatepass"
	asp-route="PassStatus"
	asp-route-linkid="@Model.GatePassId"
	asp-route-status="3"
	href="3">Lost & Exit</a>