40-Develop/gpm_web/Controllers/QuotaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using gpm_web.Models;

using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using CTX = gpm.Efc.dbsets;
using EFC = gpm.Efc;
using GC = gpm.Common;
using GCE = gpm.Common.Enums;
using SE = gpm_web.Enums;
using SC = gpm_web.Consts;
using SL = gpm_web.Lookups;
using SLD = gpm_web.Lookups.DD_Lookup;
using IA = gpm_web.Infra;
using ML = gpm_web.Models;
using stCode = gpm.Common.Enums.ErrorCode;

using static Microsoft.EntityFrameworkCore.EntityState;
using Microsoft.EntityFrameworkCore.ChangeTracking;


namespace gpm_web.Controllers
{
	/// <summary>
	/// 
	/// </summary>
	public partial class QuotaController : Infra.GPMController
	{
		public SL.DD_Lookup DDHelp { get; set; }
		public IA.DayCapacityCounters Dept_Day_Caps { get; set; }

		public QuotaController(ILogger<QuotaController> logger, GC.IAppSettingContainer App_Config, gpm.Efc.dbsets.GPM_DBContext db_context, IA.DayCapacityCounters dept_cap_counter, SL.DD_Lookup dd_helper)
			: base(logger, App_Config, db_context)
		{
			DDHelp = dd_helper;
			Dept_Day_Caps = dept_cap_counter;
		}

		// BEGIN: sak debug quota cache bug
		// show working cache of current quotas
		[Authorize("RequireAdmin")]
		public IActionResult QuotaCache()
		{
			// FOR DEBUGGIN
			log.LogWarning("==> QuotaCache");
			log.LogWarning("Building quotas for day {0}", DateTime.Now.ToString(SC.FORMATS.DATE_FORMAT));
			log.LogWarning("For debugging cache sync bug. Remove after debug. sak 2021 Jan 07");

			return View(Dept_Day_Caps.getCacheData());
		}
		// FINIS: sak debug quota cache bug

		// show current day's quotas
		[Authorize("RequireAdmin")]
		public IActionResult Index([FromForm]DateTime? dyDaySel)
		{
			log.LogDebug("==> Index");
			dyDaySel = dyDaySel ?? (DateTime?)TempData["dyDaySel"] ?? DateTime.Today;
			ViewBag.dyDay = dyDaySel;
			log.LogInformation("Get quotas for day {0}", dyDaySel?.ToString(SC.FORMATS.DATE_FORMAT));
			List<CTX.Quotas> lstQuotas = getDayQuotas((DateTime)dyDaySel);
			return View(lstQuotas);
		}

		// Show full editor
		[Authorize("RequireAdmin")]
		public IActionResult Edit(
							CTX.Quotas DeptQuota = null
							)
		{
			log.LogDebug("==> Edit");

			CTX.Quotas lqSel = null;
			bool lbOK = false;
			int liCount = 0;

			log.LogDebug("Request.HasFormContentType = {0}", Request.HasFormContentType);
			// log.LogDebug("Request.Form.Keys.Contains(\"doUpdate\") = {0}", Request.Form.Keys.Contains("doUpdate"));
			if (Request.HasFormContentType && Request.Form["doUpdate"] == "Save")
			{
				lqSel = dbcontext.Quotas
								.Where(y => y.Date == DateTime.Today && y.Department == DeptQuota.Department)
								.FirstOrDefault();
				if (lqSel == null)
				{
					log.LogError("Record not found in DB for Department = {0} [{1}]", DeptQuota.Department, DeptQuota.DeprtmentName);
					return View(new CTX.Quotas());
				}

				// update counter with new values
				lqSel.CapNewVisit = DeptQuota.CapNewVisit;
				lqSel.CapRevisit = DeptQuota.CapRevisit;
				lqSel.EditBy = UserData?.Userid ?? SC.KEYS.SYSTEM_USER_ID_VAL;
				lqSel.EditOn = DateTime.Now;

				log.LogInformation("Attempting update of current register");
				lbOK = Dept_Day_Caps.UpdateQuota(lqSel.Department, lqSel.CapNewVisit, lqSel.CapRevisit);

				if (lbOK)
				{
					log.LogInformation("Updating quotas");
					liCount = dbcontext.SaveChanges();
					log.LogDebug("Updated {0} records, saving Quota update.", liCount);
				}
				else
				{
					log.LogInformation("Current register update failed. Aborting save to database.");
				}
			}
			else
			{
				log.LogInformation("Loading data for department: {0}", DeptQuota.Department);
				if (DeptQuota?.Department > 0)
				{
					GC.DeptDayCap loCurrUse = Dept_Day_Caps.AvailaibleCapsDepartment(DeptQuota.Department);
					lqSel = dbcontext.Quotas.AsNoTracking().Where(y => y.Date == DateTime.Today && y.Department == DeptQuota.Department).FirstOrDefault();
					// Add used values also
					lqSel.UsedNewVisit = loCurrUse.UsedFirst;
					lqSel.UsedRevisit = loCurrUse.UsedRevisit;
				}
			}

			// No record found for department
			if (lqSel == null)
			{
				lqSel = new CTX.Quotas();
			}

			return View(lqSel);
		}

		// redirect to index
		[Authorize("RequireAdmin")]
		public IActionResult Put(
							  [FromForm]DateTime? dyDay = null
							, [FromForm]DateTime? dyBegin = null
							, [FromForm]DateTime? dyEnd = null
							, [FromForm]bool dyDefault = true
							, [FromForm]int flAction = 0
							, List<CTX.Quotas> quotalist = null
							)
		{
			log.LogDebug("==> Put");

			// Validate required inputs
			bool lbInputBad = false;
			switch (flAction)
			{
				case 1:
					if (dyDay == null)
					{
						lbInputBad = true;
					}
					if (lbInputBad || dyDay <= DateTime.Today)
					{
						lbInputBad = true;
					}
					break;
				case 2:
					if (lbInputBad || dyBegin == null || dyEnd == null)
					{
						lbInputBad = true;
					}
					if (lbInputBad || dyBegin >= dyEnd)
					{
						lbInputBad = true;
					}
					if (lbInputBad || dyBegin <= DateTime.Today)
					{
						lbInputBad = true;
					}
					break;
				case 9:

					break;
				default:
					log.LogError("");
					break;
			}
			if (lbInputBad)
			{
				log.LogError("Validation failed, aborting processing.");
				// return View("Index");
				return RedirectToAction("Index");
			}

			ViewBag.dyDay = dyDay ?? dyBegin ?? DateTime.Today;
			List<CTX.Quotas> lstQuotas; // = getDayQuotas((DateTime)dyDay);

			switch (flAction)
			{
				case 1:
					lstQuotas = BuildQuoteList(
									  (DateTime)dyDay
									, (DateTime)dyDay
									, Request.Form["Date"]
									, Request.Form["CapNewVisit"]
									, Request.Form["CapRevisit"]
									, Request.Form["Department"]
									);
					break;
				case 2:
					lstQuotas = BuildQuoteList(
									  (DateTime)dyBegin
									, (DateTime)dyEnd
									, Request.Form["Date"]
									, Request.Form["CapNewVisit"]
									, Request.Form["CapRevisit"]
									, Request.Form["Department"]
									);
					break;
				case 9:
					lstQuotas = BuildQuoteList(
									  DateTime.MinValue
									, DateTime.MinValue
									, Request.Form["Date"]
									, Request.Form["CapNewVisit"]
									, Request.Form["CapRevisit"]
									, Request.Form["Department"]
									);
					break;
				default:
					lstQuotas = getDayQuotas(ViewBag.dyDay);
					log.LogError("");
					return View("Index", lstQuotas);
			}

			// Add all new records to database
			DateTime ldtNow = DateTime.Now;
			int liNew = (int)SE.RECORD_STATUS.NOT_SET;
			// update timestamps
			foreach (CTX.Quotas vQ in lstQuotas)
			{
				vQ.EditBy = UserData?.Userid ?? SC.KEYS.SYSTEM_USER_ID_VAL;
				vQ.EditOn = ldtNow;
				if (vQ.Status == liNew)
				{
					vQ.Status = (int)SE.RECORD_STATUS.ACTIVE;
					vQ.AddBy = UserData?.Userid ?? SC.KEYS.SYSTEM_USER_ID_VAL;
					vQ.AddOn = ldtNow;
					dbcontext.Quotas.Add(vQ);
				}
			}

			int liRecords = dbcontext.SaveChanges();

			switch (flAction)
			{
				case 1:
					log.LogInformation("{0} records affected, updated quotas for date {1}", liRecords, dyDay?.ToString(SC.FORMATS.DATE_FORMAT));
					break;
				case 2:
					log.LogInformation(
									  "{0} records affected, updated quotas for dates {1} to {2}"
									, liRecords
									, dyBegin?.ToString(SC.FORMATS.DATE_FORMAT)
									, dyEnd?.ToString(SC.FORMATS.DATE_FORMAT)
									);
					break;
				case 9:
					log.LogInformation("{0} records affected, updated DEFAULT quotas", liRecords);
					break;
			}


			// If date is today, reset flag for counters
			if (ViewBag.dyDay == DateTime.Today)
			{
				Dept_Day_Caps.ResetInitialize();
			}

			TempData["dyDaySel"] = ViewBag.dyDay;
			return RedirectToAction("Index");

		}
	}
}

40-Develop/gpm_web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using gpm_web.Models;

using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.EntityFrameworkCore;


using Microsoft.Extensions.Logging;
using CTX = gpm.Efc.dbsets;
using EFC = gpm.Efc;
using GC = gpm.Common;
using GCE = gpm.Common.Enums;
using SE = gpm_web.Enums;
using SC = gpm_web.Consts;
using SL = gpm_web.Lookups;
using SLD = gpm_web.Lookups.DD_Lookup;
using IA = gpm_web.Infra;
using ML = gpm_web.Models;
using stCode = gpm.Common.Enums.ErrorCode;

namespace gpm_web.Controllers
{
	/// <summary>
	/// 
	/// </summary>
	public class UserController : Infra.GPMController
	{

		public UserController(ILogger<UserController> logger, GC.IAppSettingContainer App_Config, gpm.Efc.dbsets.GPM_DBContext db_context)
			: base(logger, App_Config, db_context)
		{ }

		[Authorize("RequireAdmin")]
		public IActionResult Index()
		{
			log.LogDebug("==> Index");
			List<CTX.Users> loUsers = dbcontext.Users.OrderBy(c => c.UserLogin).ToList();
			return View("Index", loUsers);
		}

		[Authorize("RequireAdmin")]
		public IActionResult Edit(int id)
		{
			log.LogDebug("==> Edit");
			CTX.Users loUser;
			if (id == 0)
			{
				loUser = new CTX.Users();
			}
			else
			{
				loUser = dbcontext.Users
							.Where(c => c.UserId == id)
							.FirstOrDefault()
							;
			}
			if (loUser == null)
			{
				PostError("Selected User does not exist in the system");
				log.LogWarning("User ID == {0} is not found in system. Inspect Requester and DB. This condition is unexpected.");
			}
			return View(loUser);
		}


		[Authorize("RequireAdmin")]
		// Used for both create and update
		public IActionResult Put(CTX.Users UserForm)
		{
			log.LogDebug("==> Put");

			// Allow blank passwords in edits.
			if (!ModelState.IsValid && !(ModelState.ErrorCount == 1 && ModelState["UserPwd"].ValidationState.ToString() == "Invalid"))
			{
				// ModelState write to error mesg
				return View("Edit", UserForm);
			}
			DateTime ldtNOW = DateTime.Now;
			// string lsHashPWD = GC.Utils.GetHashedPWD(UserForm.UserPwd);
			// log.LogDebug("Hashed {0} to {1}", UserForm.UserPwd, lsHashPWD);

			// Get entity from DB
			CTX.Users luCurrRecord = dbcontext.Users
											.Where(y => y.UserId == UserForm.UserId)
											.FirstOrDefault()
											;
			if (UserForm.UserId > 0 && luCurrRecord == null)
			{
				log.LogError("No record in Db to update. ID = {0}. Aborting further processing.", UserForm.UserId);
				// Set error message
				return View("Edit", UserForm);
			}

			if (luCurrRecord == null)
			{
				luCurrRecord = new CTX.Users();
			}

			// Update all fields
			luCurrRecord.FullName = UserForm.FullName.Trim();
			luCurrRecord.DisplayName = UserForm.DisplayName.Trim();
			luCurrRecord.UserLogin = UserForm.UserLogin.Trim().ToLower();
			luCurrRecord.Role = UserForm.Role;
			luCurrRecord.Status = UserForm.Status;
			if (!string.IsNullOrWhiteSpace(UserForm.UserPwd))
			{
				luCurrRecord.UserPwd = GC.Utils.GetHashedPWD(UserForm.UserPwd.Trim());
			}
			luCurrRecord.EditOn = ldtNOW;
			luCurrRecord.EditBy = UserData?.Userid ?? SC.KEYS.SYSTEM_USER_ID_VAL;

			if (UserForm.UserId == 0)
			{
				luCurrRecord.AddOn = ldtNOW;
				luCurrRecord.AddBy = UserData?.Userid ?? SC.KEYS.SYSTEM_USER_ID_VAL;

				// dbcontext.Add(UserForm);
				dbcontext.Users.Add(luCurrRecord);
			}

			// Save
			int liCount = dbcontext.SaveChanges();
			log.LogInformation("User save ({0}) updated {1} records.", UserForm.UserId, liCount);

			return RedirectToAction("Index");
		}

	}
}

40-Develop/gpm_web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - gpm_web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">gpm_web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <!-- <partial name="_CookieConsentPartial" /> -->
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - gpm_web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

40-Develop/gpm_web/Views/Shared/_Layout_Gpm_Public.cshtml
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8" />
	<meta name="viewport"
		  content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Gate Pass Manager</title>

	<link rel="stylesheet"
			href="~/css/gpm-fonts.css" />
	<environment include="Development">
		<link rel="stylesheet"
			  href="~/css/bootstrap-gpm.css" />
		<link rel="stylesheet"
			  href="~/css/gpm.css" />
	</environment>
	<environment exclude="Development">
		<link rel="stylesheet"
			  href="~/css/bootstrap-gpm.min.css" />
		<link rel="stylesheet"
			  href="~/css/gpm.min.css" />
	</environment>
	<link rel="stylesheet"
		  href="~/css/site.css" />
</head>

<body>
	<header>
		<!-- Mast Head -->
		<nav class="navbar bg-light border-bottom shadow-light mb-0">
			<div class="d-flex align-items-center w-100">
				<div class="d-flex align-items-start flex-fill align-items-baseline">
					<a class="h1 pl-3 shadow-text-outline text-cstm-dark"
					   asp-controller="Session"
					   asp-action="Login">Gate Pass Manager</a>
					<div>
						<div class="d-block d-sm-none mx-2">XS </div>
						<div class="d-none d-sm-block mx-2 d-md-none">SM </div>
						<div class="d-none d-md-block mx-2 d-lg-none">MD </div>
						<div class="d-none d-lg-block mx-2 d-xl-none">LG </div>
						<div class="d-none d-xl-block mx-2">XL </div>
					</div>
					<div class="pl-3 text-black-50 d-none d-sm-inline">Process, Track and Manage Gate Passes. And some
						very long text asdfadfasdfgasdfasdf asdfasdfasd asdfasf asdfasdf asdfasd dfgh fgh.</div>
				</div>
			</div>
		</nav>
	</header>

	<!-- ========================================================================================================== -->

	<div class="container-fluid">
		<!-- <partial name="_CookieConsentPartial" /> -->
		<main role="main"
			  class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container text-center">
			Developed by Novelty Data Solutions LLP
		</div>
	</footer>

	<environment include="Development">
		<script src="~/lib/jquery/dist/jquery.js"></script>
		<script src="~/js/bootstrap-gpm.js"></script>
		<script src="~/js/gpm.js"></script>
	</environment>
	<environment exclude="Development">
		<script src="~/lib/jquery/dist/jquery.min.js"></script>
		<script src="~/js/bootstrap-gpm.min.js"></script>
		<script src="~/js/gpm.min.js"></script>
	</environment>
	<script src="~/js/site.js"
			asp-append-version="true"></script>

	@RenderSection("Scripts", required: false)
</body>

</html>

40-Develop/gpm_web/Views/Shared/_Layout_Gpm_User.cshtml
@using Microsoft.Extensions.Logging;
@using CTX = gpm.Efc.dbsets;
@using EFC = gpm.Efc;
@using GC = gpm.Common;
@using GCE = gpm.Common.Enums;
@using SE = gpm_web.Enums;
@using SC = gpm_web.Consts;
@using SL = gpm_web.Lookups;
@using SLD = gpm_web.Lookups.DD_Lookup;
@using IA = gpm_web.Infra;
@using ML = gpm_web.Models;
@using stCode = gpm.Common.Enums.ErrorCode;

<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8" />
	<meta name="viewport"
		  content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Gate Pass Manager</title>

	<link rel="stylesheet"
			href="~/css/gpm-fonts.css" />
	<environment include="Development">
		<link rel="stylesheet"
			  href="~/css/bootstrap-gpm.css" />
		<link rel="stylesheet"
			  href="~/css/gpm.css" />
	</environment>
	<environment exclude="Development">
		<link rel="stylesheet"
			  href="~/css/bootstrap-gpm.min.css" />
		<link rel="stylesheet"
			  href="~/css/gpm.min.css" />
	</environment>
	<link rel="stylesheet"
		  href="~/css/site.css" />
</head>

@{
	string lsUserName = "Anonymous";
	bool lbIsAdmin = false;
	string lsRole = "";
	if (User.Identity.IsAuthenticated)
	{
		lsUserName = User.Identity.Name;
		lbIsAdmin = User.HasClaim(System.Security.Claims.ClaimTypes.Role, SC.USER_ROLES.ADMIN);
		lsRole = User.Claims.Where(y => y.Type == System.Security.Claims.ClaimTypes.Role).FirstOrDefault()?.Value ?? "";
	}
	
	// just to catch debugger
	int liCount = User.Claims.Count();

}



<body>
	<header>
		<!-- Mast Head -->
		<nav class="navbar bg-light mb-0">
			<div class="d-flex align-items-center w-100">
				<div class="d-flex align-items-start flex-fill align-items-baseline">
					<a class="h1 pl-3 shadow-text-outline text-cstm-dark"
					   asp-controller="Home"
					   asp-action="Index">Gate Pass Manager</a>
					<div class="pl-3 text-black-50 d-none d-sm-inline text-monospace">Process, Track and Manage Gate Passes.</div>
				</div>
				<div class="d-flex flex-column justify-content-end">
					<div class="text-right text-cstm-dark">@lsUserName</div>
				</div>
			</div>
		</nav>
		<!-- Menu bar -->
		<!-- TODO:
			Render menu based on user role
			1. User
			2. Admin
			3. Operator
		-->
		<div class="container-fluid d-none d-sm-block py-1 border-bottom mb-1">
			@switch (lsRole)
			{
				case SC.USER_ROLES.ADMIN:
					<nav class="nav nav-pills nav-justified w-100">

						<div class="nav-item dropdown bg-cstm-pri-light mx-1 shadow-light">
							<a class="nav-link dropdown-toggle"
								data-toggle="dropdown"
								href="#"
								role="button"
								aria-haspopup="true"
								aria-expanded="false">Gatepass</a>
							<div class="dropdown-menu bg-cstm-sec-light w-100">
								<a class="dropdown-item bg-cstm-sec-light w-100"
									asp-controller="GatePass"
									asp-action="Find"
									asp-route-linkid="0">Search Gatepass</a>
								<a class="dropdown-item bg-cstm-sec-light w-100"
									asp-controller="GatePass"
									asp-action="FindOne">Find One Gatepass</a>
								<a class="dropdown-item bg-cstm-sec-light w-100"
									asp-controller="GatePass"
									asp-action="TypeSelect">New Visitor/EM pass</a>
								<a class="dropdown-item bg-cstm-sec-light w-100"
									asp-controller="GatePass"
									asp-action="DeptSelect">New Patient Gatepass</a>
							</div>
						</div>

						<a class="nav-item nav-link text-black-50 btn-cstm-alt-2-light mx-1 shadow-light"
							asp-controller="Quota"
							asp-action="Index">View Quotas</a>

						<a class="nav-item nav-link text-black-50 btn-cstm-alt-2-light mx-1 shadow-light"
							asp-controller="Quota"
							asp-action="Edit">Edit Quota</a>

						<a class="nav-item nav-link text-black-50 btn-cstm-alt-2-light mx-1 shadow-light"
							asp-controller="User"
							asp-action="Index">Users</a>

					</nav>
					break;
				case SC.USER_ROLES.USER:
					<nav class="nav nav-pills nav-justified p-2">
						<a class="nav-item nav-link text-black-50 bg-cstm-pri-light mx-1 shadow-light"
						   asp-controller="GatePass"
						   asp-action="DeptSelect">Patient Pass</a>
						<a class="nav-item nav-link text-black-50 bg-cstm-pri-light mx-1 shadow-light"
						   asp-controller="GatePass"
						   asp-action="TypeSelect"
						   asp-route-linkid="0">New Visitor/EM pass</a>
						<a class="nav-item nav-link text-black-50 bg-cstm-pri-light mx-1 shadow-light"
						   asp-controller="GatePass"
						   asp-action="FindOne">Find One Gatepass</a>
						<a class="nav-item nav-link text-black-50 bg-cstm-pri-light mx-1 shadow-light"
						   asp-controller="GatePass"
						   asp-action="Find"
						   asp-route-linkid="0">Search</a>
					</nav>
					break;
				default:
					<div class="h1">Unknown Role - No menu generated.</div>
					break;
			}



		</div>
	</header>
	<div class="container-fluid">
		<!-- <partial name="_CookieConsentPartial" /> -->
		<main role="main"
			  class="pb-3">
			<!---------------------------------------------------------------- 
				VIEW CONTENT - BEGIN
			---------------------------------------------------------------->
			@RenderBody()
			<!---------------------------------------------------------------- 
				VIEW CONTENT - END
			---------------------------------------------------------------->
		</main>
	</div>

	<footer class="border-top footer text-muted bg-light p-1">
		<div class="container text-center h6 small">
			Developed by Novelty Data Solutions LLP
		</div>
	</footer>

	<environment include="Development">
		<script src="~/js/jquery.js"></script>
		<script src="~/js/jquery.validate.js"></script>
		<script src="~/js/additional-methods.js"></script>
		<script src="~/js/jquery.validate.unobtrusive.js"></script>
		<script src="~/js/bootstrap-gpm.bundle.js"></script>
		<script src="~/js/gpm.js"></script>
	</environment>
	<environment exclude="Development">
		<script src="~/js/jquery.min.js"></script>
		<script src="~/js/jquery.validate.min.js"></script>
		<script src="~/js/additional-methods.min.js"></script>
		<script src="~/js/jquery.validate.unobtrusive.min.js"></script>
		<script src="~/js/bootstrap-gpm.bundle.min.js"></script>
		<script src="~/js/gpm.min.js"></script>
	</environment>
	<script src="~/js/site.js"
			asp-append-version="true"></script>
	<script>
		$(document).ready(doDocumentReadyActions());

	</script>

	@RenderSection("pageScript", required: false)
</body>

</html>